### ISSUE TITLE
UnifiedLogger: When the memory map is full it fails at resizing it.

### ISSUE THREAD

**Issue by gbin** [copper-project/copper-rs#1]
And it generates a nasty Out Of Memory panic.

**Comment by makeecat** [comment]
OS: Ubuntu 22.04 with x64 arch

When I try to run the example by
```
cd examples/cu_caterpillar
cargo run --release
```

I got this log, I assume it is related.
```
Log Used 99MB
thread 'main' panicked at cu29_unifiedlog/src/lib.rs:400:14:
Failed to resize memory map: Os { code: 12, kind: OutOfMemory, message: "Cannot allocate memory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at cu29_unifiedlog/src/lib.rs:130:58:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x5c5e1b0216b4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd736fd5964392270
   1:     0x5c5e1afae92b - core::fmt::write::hc6043626647b98ea
   2:     0x5c5e1b022bd7 - std::sys_common::backtrace::print::h45eb8174d25a1e76
   3:     0x5c5e1b022944 - std::panicking::default_hook::{{closure}}::haf3f0170eb4f3b53
   4:     0x5c5e1b0234b9 - std::panicking::rust_panic_with_hook::h6b49d59f86ee588c
   5:     0x5c5e1b022e34 - std::panicking::begin_panic_handler::{{closure}}::hd4c2f7ed79b82b70
   6:     0x5c5e1b022d89 - std::sys_common::backtrace::__rust_end_short_backtrace::h2946d6d32d7ea1ad
   7:     0x5c5e1b022d76 - rust_begin_unwind
   8:     0x5c5e1afa8202 - core::panicking::panic_fmt::ha02418e5cd774672
   9:     0x5c5e1afa8625 - core::result::unwrap_failed::h55f86ada3ace5ed2
  10:     0x5c5e1afd1215 - <cu29_unifiedlog::MmapStream as core::ops::drop::Drop>::drop::hc9a7207e92396497
  11:     0x5c5e1afac1ac - core::ptr::drop_in_place<cu29_unifiedlog::MmapStream>::hab7e4f3bfd9a94e9
  12:     0x5c5e1afdeedc - core::ptr::drop_in_place<cu_caterpillar::CaterpillarApplication>::h4e397a106874f8cf
  13:     0x5c5e1afdeb7a - cu_caterpillar::main::h2b674957bb56f26d
  14:     0x5c5e1afe2703 - std::sys_common::backtrace::__rust_begin_short_backtrace::hed241c41a1f8a5a0
  15:     0x5c5e1afd2e0d - main
  16:     0x738103429d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  17:     0x738103429e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  18:     0x5c5e1afabc65 - _start
  19:                0x0 - <unknown>
thread 'main' panicked at library/core/src/panicking.rs:227:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
[1]    19295 IOT instruction (core dumped)  cargo run --release
```

**Comment by gbin** [comment]
Yes this is exactly that, for now just allocate more on disk if needed. I am thinking about building a slab system where we add another file. The resizing in place doesn't work for some reason on my side too.

**Comment by gbin** [comment]
resolved and merged
