### ISSUE TITLE
Logger is crashing logging images 

### ISSUE THREAD

**Issue by gbin** [copper-project/copper-rs#183]
From @edgarriba

![image](https://github.com/user-attachments/assets/2f869183-0b9a-4413-ac39-ebc2d85bd4ae)

Trying: https://github.com/kornia/kornia-rs/pull/193/files

**Comment by gbin** [comment]
I really wonder if the panic created the core dump or the core dump created the panic Oo

**Comment by edgarriba** [comment]
To unblock myself of using copper, is it possible disable the logger ?

**Comment by edgarriba** [comment]
@gbin any progress here ? I'm blocked to use copper for now

**Comment by gbin** [comment]
Ok I understood what is going on.

The logger preallocates pages based on the size of the CopperList (the assumption was that what you log will be part of the copperlist) but in your case because your message do allocate outside of it, the CopperList is very small, it allocates the space for 64 for them but it is still smaller than one image.

I will put a config parameter in the ron file to override that for now to unblock us. Then with the other work I am doing on the buffer pools, I'll see if I can deduce a correct allocation size.

**Comment by gbin** [comment]
@edgarriba can you try with https://github.com/copper-project/copper-rs/pull/186
adding this section to the ron file:
 logging: (
        section_size_mib: 100, // put here in Mibibytes roughly ~64x the size of everything your tasks will produce for one cycle.
    ),

Note: once we have the buffer pools finalized the runtime should be able to make this decision by itself.

**Comment by edgarriba** [comment]
```bash
edgar@farmng-TensorBook-late-2021:~/software/kornia-rs$ RUST_BACKTRACE=1 RUST_LOG=info cargo run --bin copper
warning: /home/edgar/software/kornia-rs/examples/copper_pipeline/Cargo.toml: unused manifest key: dependencies.cu29.sha
warning: /home/edgar/software/kornia-rs/examples/copper_pipeline/Cargo.toml: unused manifest key: dependencies.cu29-helpers.sha
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.33s
     Running `target/debug/copper`
Webcam::start
[2024-12-29T18:17:02Z INFO  re_sdk_comms::server] New SDK client connected from: 127.0.0.1:44692
Webcam::start
RerunViz::process: logging image: ImageSize { width: 640, height: 480 }
RerunViz::process: logged image
thread 'main' panicked at /home/edgar/.cargo/git/checkouts/copper-rs-b1305cc2c7d30d00/92a180a/core/cu29_unifiedlog/src/lib.rs:111:22:
Failed to encode object in a newly minted section. Unrecoverable failure.: UnexpectedEnd
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1700:5
   3: core::result::Result<T,E>::expect
             at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1061:23
   4: <cu29_unifiedlog::MmapStream as cu29_traits::WriteStream<E>>::log
             at /home/edgar/.cargo/git/checkouts/copper-rs-b1305cc2c7d30d00/92a180a/core/cu29_unifiedlog/src/lib.rs:106:34
   5: cu29_runtime::curuntime::CuRuntime<CT,P,M,_>::end_of_processing::{{closure}}
             at /home/edgar/.cargo/git/checkouts/copper-rs-b1305cc2c7d30d00/92a180a/core/cu29_runtime/src/curuntime.rs:87:17
   6: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:810:29
   7: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:294:13
   8: core::iter::traits::double_ended::DoubleEndedIterator::rfold
             at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/double_ended.rs:308:21
   9: <core::iter::adapters::rev::Rev<I> as core::iter::traits::iterator::Iterator>::fold
             at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/rev.rs:64:9
  10: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold
             at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/chain.rs:123:19
  11: core::iter::traits::iterator::Iterator::for_each
             at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:813:9
  12: cu29_runtime::curuntime::CuRuntime<CT,P,M,_>::end_of_processing
             at /home/edgar/.cargo/git/checkouts/copper-rs-b1305cc2c7d30d00/92a180a/core/cu29_runtime/src/curuntime.rs:79:9
  13: copper::KorniaApplication::run_one_iteration
             at ./examples/copper_pipeline/src/main.rs:6:1
  14: copper::KorniaApplication::run
             at ./examples/copper_pipeline/src/main.rs:6:1
  15: copper::main
             at ./examples/copper_pipeline/src/main.rs:24:5
  16: core::ops::function::FnOnce::call_once
             at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at /home/edgar/.cargo/git/checkouts/copper-rs-b1305cc2c7d30d00/92a180a/core/cu29_unifiedlog/src/lib.rs:131:58:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x55fa33d8f1fa - std::backtrace_rs::backtrace::libunwind::trace::h5a5b8284f2d0c266
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x55fa33d8f1fa - std::backtrace_rs::backtrace::trace_unsynchronized::h76d4f1c9b0b875e3
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fa33d8f1fa - std::sys::backtrace::_print_fmt::hc4546b8364a537c6
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys/backtrace.rs:66:9
   3:     0x55fa33d8f1fa - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h5b6bd5631a6d1f6b
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys/backtrace.rs:39:26
   4:     0x55fa33db9003 - core::fmt::rt::Argument::fmt::h270f6602a2b96f62
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/fmt/rt.rs:177:76
   5:     0x55fa33db9003 - core::fmt::write::h7550c97b06c86515
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/fmt/mod.rs:1186:21
   6:     0x55fa33d8b913 - std::io::Write::write_fmt::h7b09c64fe0be9c84
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/io/mod.rs:1839:15
   7:     0x55fa33d8f042 - std::sys::backtrace::BacktraceLock::print::h2395ccd2c84ba3aa
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys/backtrace.rs:42:9
   8:     0x55fa33d8ffdc - std::panicking::default_hook::{{closure}}::he19d4c7230e07961
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:268:22
   9:     0x55fa33d8fe22 - std::panicking::default_hook::hf614597d3c67bbdb
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:295:9
  10:     0x55fa33d905b7 - std::panicking::rust_panic_with_hook::h8942133a8b252070
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:801:13
  11:     0x55fa33d9044a - std::panicking::begin_panic_handler::{{closure}}::hb5f5963570096b29
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:674:13
  12:     0x55fa33d8f6d9 - std::sys::backtrace::__rust_end_short_backtrace::h6208cedc1922feda
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/sys/backtrace.rs:170:18
  13:     0x55fa33d900dc - rust_begin_unwind
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
  14:     0x55fa336b2df0 - core::panicking::panic_fmt::h0c3082644d1bf418
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
  15:     0x55fa336b3276 - core::result::unwrap_failed::hd20b4aa073bda1e2
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1700:5
  16:     0x55fa33c8f29d - core::result::Result<T,E>::unwrap::h6fe15b6b4a7a9ebf
                               at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1104:23
  17:     0x55fa33c8f29d - <cu29_unifiedlog::MmapStream as core::ops::drop::Drop>::drop::hb95c0cefc6b4e743
                               at /home/edgar/.cargo/git/checkouts/copper-rs-b1305cc2c7d30d00/92a180a/core/cu29_unifiedlog/src/lib.rs:131:32
  18:     0x55fa33c59ba7 - core::ptr::drop_in_place<cu29_unifiedlog::MmapStream>::h850ceb30537692c2
                               at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:574:1
  19:     0x55fa336b3ff4 - core::ptr::drop_in_place<alloc::boxed::Box<dyn cu29_traits::WriteStream<cu29_runtime::copperlist::CopperList<copper::CuMsgs>>>>::h554aa5232cb92e7f
                               at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:574:1
  20:     0x55fa336b40e7 - core::ptr::drop_in_place<cu29_runtime::curuntime::CuRuntime<(copper::tasks::webcam::Webcam,copper::tasks::rerun_viz::RerunViz),copper::CuMsgs,cu29_runtime::monitoring::NoMonitor,10_usize>>::h5f80054dda8aced9
                               at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:574:1
  21:     0x55fa336b417a - core::ptr::drop_in_place<copper::KorniaApplication>::hfd18a4c327b7945e
                               at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:574:1
  22:     0x55fa336b8060 - copper::main::h070118ca760338a1
                               at /home/edgar/software/kornia-rs/examples/copper_pipeline/src/main.rs:31:1
  23:     0x55fa336b3e3b - core::ops::function::FnOnce::call_once::ha4d566dbaa4f2e35
                               at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  24:     0x55fa336b7d5e - std::sys::backtrace::__rust_begin_short_backtrace::he770c31917f8c93e
                               at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:154:18
  25:     0x55fa336c3f61 - std::rt::lang_start::{{closure}}::h1fd78854f6a19bbe
                               at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:195:18
  26:     0x55fa33d857fe - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfdb85f4ee94732d3
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/ops/function.rs:284:13
  27:     0x55fa33d857fe - std::panicking::try::do_call::h6e577310f330cbef
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:557:40
  28:     0x55fa33d857fe - std::panicking::try::ha588d438267d2645
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:520:19
  29:     0x55fa33d857fe - std::panic::catch_unwind::h429fda1e025f26d9
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panic.rs:358:14
  30:     0x55fa33d857fe - std::rt::lang_start_internal::{{closure}}::h7b731265e841c4bf
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/rt.rs:174:48
  31:     0x55fa33d857fe - std::panicking::try::do_call::hc0f6a675b7ae5a36
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:557:40
  32:     0x55fa33d857fe - std::panicking::try::h4c93b7ff0671f1ff
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:520:19
  33:     0x55fa33d857fe - std::panic::catch_unwind::hcc1e154961d16ce6
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panic.rs:358:14
  34:     0x55fa33d857fe - std::rt::lang_start_internal::h1c66660c99c8424c
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/rt.rs:174:20
  35:     0x55fa336c3f3a - std::rt::lang_start::h5fcd3188c364b780
                               at /home/edgar/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:194:17
  36:     0x55fa336c303e - main
  37:     0x7f9371d34083 - __libc_start_main
                               at /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:308:16
  38:     0x55fa336b37fe - _start
  39:                0x0 - <unknown>
thread 'main' panicked at core/src/panicking.rs:229:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.
Aborted (core dumped)
```

**Comment by gbin** [comment]
That is strange, what is the size of the section you put?

**Comment by edgarriba** [comment]
`const SLAB_SIZE: Option<usize> = Some(100 * 1024 * 1024);` but i don't have any reference why this numbers at all

**Comment by gbin** [comment]
oh I have added a new config in the .ron file in this PR!
see the example:
```
(
    tasks: [
        (
            id: "task0",
            type: "tasks::ExampleSrc",
        ),
        (
            id: "task1",
            type: "tasks::ExampleTask",
        ),
        (
            id: "task2",
            type: "tasks::ExampleSink",
        ),
     ],
    cnx: [
        (src: "task0", dst: "task1", msg: "i32"),
        (src: "task1", dst: "task2", msg: "i32"),
    ],

    logging: (
        slab_size_mib: 1024, // Preallocates 1GiB of memory map file at a time
        section_size_mib: 100, // Preallocates 100MiB of memory map per section for the main logger.
    ),
)
```
section_size_mib <- this is the one that you need to bump up.

**Comment by gbin** [comment]
FYI, a SLAB is basically the size of the memory mapped files Copper preallocates (those _0, _1... files you see need to be fixed size)
within those memory mapped files, Copper will interleave all the different streams from the system but every time will reserve some space to have some runway to write into. This is what the section_size is, basically it needs to be *at least* be able to log one loop. The issue is that originally it was designed guessing the amount to pre reserve from the size of the output of your tasks, now that we start to have data that is outside of the output (in memory pools) it guesses very wrong and the section is way too small to even log one image then freaks out.
